#### Group 7    
#### Suzan Adel Anis    
#### Mohamed Ahmed Mohamed

In [7]:
#Import importatnt 
%config Completer.use_jedi=False
from jupyter_dash import JupyterDash #better for notebooks
from dash import html
from  dash import dcc,callback_context
from dash.dependencies import Input,Output,State
import pandas as pd
import numpy as np
import base64
import plotly.io as pio
import dash_daq as daq
import plotly.express as px

### Data Exploration

In [8]:
df = pd.read_csv("netflix_titles.csv")
iso_df = pd.read_csv("wikipedia-iso-country-codes.csv")
display(df.head())
display(df.info())
iso_df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,25-Sep-21,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,24-Sep-21,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,24-Sep-21,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,24-Sep-21,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,24-Sep-21,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

None

,English short name lower case,Alpha-2 code,Alpha-3 code,Numeric code,ISO 3166-2
0,Zimbabwe,ZW,ZWE,716,ISO 3166-2:ZW
1,Zambia,ZM,ZMB,894,ISO 3166-2:ZM
2,Yemen,YE,YEM,887,ISO 3166-2:YE
3,Western Sahara,EH,ESH,732,ISO 3166-2:EH
4,Wallis and Futuna,WF,WLF,876,ISO 3166-2:WF

### Adding 'Alpha-3 code' column

In [9]:
df=df.merge(iso_df[['English short name lower case',"Alpha-3 code"]],how='left',left_on="country",right_on="English short name lower case").drop(columns=['English short name lower case'])

In [10]:
display(df.head())
df.info()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Alpha-3 code
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,25-Sep-21,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",USA
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,24-Sep-21,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",ZAF
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,24-Sep-21,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,NaN
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,24-Sep-21,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",NaN
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,24-Sep-21,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,IND

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8807 entries, 0 to 8806
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
 12  Alpha-3 code  6602 non-null   object
dtypes: int64(1), object(12)
memory usage: 963.3+ KB

### Dealing with multiple categories

In [11]:
cat_series = df.set_index('show_id')\
                .listed_in.str.split(', ', expand=True)\
                .stack().reset_index(level=1, drop=True);
cat_series

show_id
s1                  Documentaries
s2         International TV Shows
s2                      TV Dramas
s2                   TV Mysteries
s3                 Crime TV Shows
                   ...
s8806    Children & Family Movies
s8806                    Comedies
s8807                      Dramas
s8807        International Movies
s8807            Music & Musicals
Length: 19323, dtype: object

In [14]:
fig = px.scatter_geo()
app=JupyterDash()
# Define the theme
theme = {
    'dark': True,
    'detail': '#007439',
    'primary': '#00EA64',
    'secondary': '#6E6E6E',
}

app.layout =html.Div([
    # Title 
    html.H1('Netflix Analysis', style={'textAlign':'center', 'color':'red', 'backgroundColor':'#111111'}),
    
    # Select All Button
    html.Button(id='Select_All_B',n_clicks=0,children='Select All',
               style={'display': 'inline-block', 'vertical-align': 'middle',
                      'color':'white',
                      'backgroundColor': '#545ccc',
                  "min-width": "150px",
                   'height': "25px",
                   "margin-top": "0px",
                   "margin-left": "5px"}
                    ,className='plotly_dark'),
    # Clear Selection Button
    html.Button(id='Clear_Selection_B',n_clicks=0,children='Clear Selection',
               style={'display': 'inline-block', 'vertical-align': 'middle',
                      #'backgroundColor': '#545ccc',
                      'color':'white',
                      'backgroundColor': 'red',
                  "min-width": "150px",
                   'height': "25px",
                   "margin-top": "0px",
                   "margin-left": "20px"}
                   ),
    
    # Checklist of all Media Categories
    dcc.Checklist(
        id='categories_CL',
        options=[
             # "value_counts" to make values appear in drop down list ordered descendingly
            {'label': cat, 'value': cat} for cat in cat_series.value_counts().index 
        ],
        value=cat_series.value_counts().index[:1],
        labelStyle={'width': '20%','display': 'inline-block'},
        style={'color':'white'}
    ),
    
    # Globe Graph
    dcc.Graph(id='Geo_Graph',figure=fig,style={'backgroundColor':'#111111'}),
    
    # Year Range Slider
    dcc.RangeSlider(
        id='years_RS',
        #count=1,
        min=df['release_year'].min(),
        max=df['release_year'].max(),
        step=None,
        value=[df['release_year'].value_counts().index[20],df['release_year'].value_counts().index[50]],
        marks={str(year): {'label':str(year),'style':{'color': '#77b0b1', 'fontSize': 14,'transform':'rotate(70deg)'}} for year in df['release_year'].unique()},
        tooltip={"placement": "bottom", "always_visible": True}
    )    
],style={'backgroundColor':'#111111'})


@app.callback(
    Output(component_id='Geo_Graph',component_property='figure'),
    Output(component_id='categories_CL',component_property='value'),
    Input(component_id='categories_CL',component_property='value'),
    Input(component_id='years_RS',component_property='value'),
    Input('Select_All_B', 'n_clicks'),
    Input('Clear_Selection_B', 'n_clicks')
)


def update_Div(category_list,years,n_1,n_2):
    changed_id = [p['prop_id'] for p in callback_context.triggered][0]
    # Show empty globe graph when we clear selection (instead of empty grid graph)
    if 'Select_All_B' in changed_id:
        category_list=list(cat_series.value_counts().index)
    elif 'Clear_Selection_B' in changed_id:
        category_list=[]
        
    # Listing all selected years from range slider    
    years=list(map(int, years))
    years_list=df['release_year'].unique()[(df['release_year'].unique()>=min(years))&(df['release_year'].unique()<=max(years))]
    masked_df=df[df['release_year'].isin(list(set(years_list)))]
    
    # Listing only the selected categories from the checklist
    ids=list(cat_series[cat_series.isin(category_list)].index)
    masked_df=masked_df[masked_df['show_id'].isin(ids)]
    locs="Alpha-3 code"
    _zeroflag=0
    if len(masked_df)==0:
        _zeroflag=1
        masked_df=df.iloc[:5]
        
    # Dealing with Media that was created from multiple countries 
    filtered_countries = pd.DataFrame(masked_df.set_index('show_id').country.str.split(', ', expand = True).stack().reset_index(level=1, drop=True));
    filtered_countries = filtered_countries.reset_index()
    
    filtered_countries.columns = ['title','country']
    filtered_countries = filtered_countries.merge(iso_df[['English short name lower case',"Alpha-3 code"]],\
                how ='left',left_on = 'country',right_on = "English short name lower case")\
                .drop(columns = ['English short name lower case'])
    # Dealing with null countries
    filtered_countries = filtered_countries[filtered_countries.country != 'Country Unavailable']
    filtered_countries = filtered_countries.dropna()
    
    # Counting each country Media in the filtered dataframe
    counts = filtered_countries['Alpha-3 code'].value_counts()
    
    locs=filtered_countries['Alpha-3 code'].value_counts().index

    if _zeroflag==1:
        locs=filtered_countries['country'].value_counts().index
    
    # Plotting the globe with the size of Media relased with the selected filters
    fig = px.scatter_geo( locations=locs,template='plotly_dark',
                     hover_name = filtered_countries["country"].value_counts().index,
                     projection = "natural earth",size = counts,opacity = 0.8,size_max=60,width=1200,height=600)
    fig.update_layout(
        title={
            'text': "Distribution of Media categories over years",
            'y':0.95,
            'x':0.5,
            'xanchor': 'center',
            'yanchor': 'top'}
        )
    return fig,category_list
    
app.run_server()

Dash app running on http://127.0.0.1:8050/